### ISSUE TITLE
Show articles in the article feed

### ISSUE THREAD

**Issue by ericdudley** [agblox/ui_proto#5]
Consume the `/articles` API endpoint to be able to show articles.

Depends on the endpoint being created in [research-lab/#43](https://github.com/agblox/research-lab/issues/43).

Currently can kind of fake it by consuming `/tweets` endpoint.

# Tasks
- [x] Create article UI component
- [x] Consume `/articles` to get recent articles
- [x] Filter by "contains text" field
- [x] Filter by "time range" field

# Blockers
- [x] API does not provide links to the original tweet

**Comment by tbosch82** [comment]
This is done for now, until we have more article endpoints to consume.
