### ISSUE TITLE
Graphing Auction Data

### ISSUE THREAD

**Issue by tbosch82** [agblox/ui_proto#62]
Auction house data needs to be visualized in UI

## Tasks
- [x] Implement GIS heatmap in UI
- [ ] access endpoint to retrieve auction house data

## Blockers
- [x] GIS heatmap graphing software
- [ ] Endpoint to access auction data

**Comment by tbosch82** [comment]
Complete
