### ISSUE TITLE
Training Tab

### ISSUE THREAD

**Issue by tbosch82** [agblox/ui_proto#71]
Training tab needs completion.

## ToDo
- [x] Add new sources to train from
- [ ] Change sources being trained
- [x] View processed articles
- [x] Access processed articles (URLs)
- [ ] Highlight relevant phrases given from NLP
- [x] Add/edit data tags for individual articles
- [ ] Add/edit data tags master list

**Comment by tbosch82** [comment]
Initial build in #66

**Comment by tbosch82** [comment]
Waiting for UI/UX
