### ISSUE TITLE
Create paper trading page

### ISSUE THREAD

**Issue by ericdudley** [agblox/ui_proto#9]
# Trading Page
First version of paper trading is deployed. This version simulated market orders by getting the current quote from the backend, and calculating/executing orders in the front-end. This solution is not secure, and not accurate, as it uses ten-minute delayed quotes. Likewise, it does not support limit orders.

The paper trading will track held securities across multiple portfolios. A better long-term solution would be to switch to a third-party service for managing portfolios and simulating order execution. Ideally this third-party service would provide APIs for both paper trading and actual trading for a more reliable and seamless integration.

## Tasks
- [x] Get initial ideas from Tony
- [x] Put together initial scaffold
- [x] Gather requirements and update [research-lab/#44](https://github.com/agblox/research-lab/issues/44)
- [x] Consume API endpoints
- [ ] Explore 3rd-party services

**Comment by tbosch82** [comment]
Initial build (#12) merged with master.
